FROM python:3.10-slim

RUN pip install --no-cache-dir \
    numpy==1.24.4 \
    pandas==1.5.3 \
    evidently==0.4.16 \
    prometheus-client==0.20.0

RUN mkdir -p /app/monitoring /app/data

WORKDIR /app

COPY monitoring/evidently_service.py /app/monitoring/evidently_service.py
COPY monitoring/inference_log.csv /app/monitoring/inference_log.csv
COPY data/EasyVisa.csv /app/data/EasyVisa.csv

EXPOSE 8085
CMD ["python", "/app/monitoring/evidently_service.py"]
