apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: easyvisa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.10-slim
        command:
        - "/bin/sh"
        - "-c"
        - "pip install mlflow==3.10.1 boto3 --quiet && mlflow server --backend-store-uri sqlite:////tmp/mlflow.db --artifacts-destination s3://easyvisa-mlflow-vision-2025/mlflow-artifacts --host 0.0.0.0 --port 5000"
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: easyvisa-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: easyvisa-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: easyvisa-secrets
              key: AWS_DEFAULT_REGION
        - name: MLFLOW_SERVER_ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: easyvisa
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000